### ISSUE TITLE
use aiohttp instead of requests

### ISSUE THREAD

**Issue by helish88** [ViZus-s/Disnake-Statistics-Bot#4]
https://github.com/ViZus-s/Libstats-bot/blob/0dce0e53fd4076bd87d90d1f54afcb31fb5c81d6/parsers/github.py#L3

**Comment by ViZus-s** [comment]
I will check tomorrow this issue.

**Comment by ViZus-s** [comment]
Today or tomorrow repository will be updated.
Thank you for feedback.
